
apiVersion: apps/v1
kind: Deployment
metadata:
  name: writer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: writer
  template:
    metadata:
      labels:
        app: writer
    spec:
      containers:
      - name: content
        image: alpine:latest
        volumeMounts:
        - name: html
          mountPath: /html
        command: ["/bin/sh", "-c"]
        args:
        - var1=0
          touch /html/abc;
          while true; do
          date >> /html/index.html;
          sleep 5;
          var1=$(($var1+1));
          if [ $var1 -ge 12 ]; then rm -rf /html/abc; fi
          done
        livenessProbe:
          exec:
            command:
            - cat
            - /html/abc
          initialDelaySeconds: 5
          periodSeconds: 5
      nodeSelector:
        name: node
      volumes:
      - name: html
        persistentVolumeClaim:
          claimName: html

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: reader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reader
  template:
    metadata:
      labels:
        app: reader
    spec:
      containers:
      - name: nginx
        image: nginx:stable-alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
          readOnly: true
      nodeSelector:
        name: node
      volumes:
      - name: html
        persistentVolumeClaim:
          claimName: html

---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: html
  labels:
    type: hostpath
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  storageClassName: html
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    type: DirectoryOrCreate
    path: "/tmp/html"

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: html
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: html
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: Service
metadata:
  name: reader
spec:
  type: NodePort
  selector:
    app: reader
  ports:
  - nodePort: 32410
    protocol: TCP
    port: 80
    targetPort: 80

