apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoinmem
spec:
  selector:
    matchLabels:
      app: todoinmem
  template:
    metadata:
      labels:
        app: todoinmem
    spec:
      containers:
      - name: todoinmemc
        image: vijaynvb/todoinm:latest
        ports:
        - containerPort: 8080 

---

apiVersion: v1
kind: Service
metadata:
  name: todosvc
spec:
  type: NodePort
  selector:
    app: todoinmem
  ports:
  - port: 8080
    targetPort: 8080

