apiVersion: v1
kind: Pod
metadata:
  name: alpine
  namespace: default
  labels:
    app: alpine
spec:
  containers:
  - image: alpine:latest
    command:
      - sleep
      - "5000"
    imagePullPolicy: IfNotPresent
    name: latest
  restartPolicy: Always